#!/bin/sh

wallpaper_path=$(realpath "$1")

parent_path=$( cd "$(dirname "$0")" ; pwd -P )
cd "$parent_path"

list_wallpapers() {
    for file in "$1"/*
    do
        if [ -f "$file" ]; then
            printf "%s\0icon\037%s\n" "$(basename "$file")" "$(realpath "$file")"
        fi
    done
}

selected_wallpaper="$(list_wallpapers "$wallpaper_path" | rofi -p "Choose a wallpaper" -i -dmenu -config "$XDG_CONFIG_HOME/rofi/images.rasi")"

if [ -z "$selected_wallpaper" ]; then
    exit 0;
fi

realpath "$1/$selected_wallpaper"
