#!/usr/bin/env bash
file=$1

mime=$(file -Lb --mime-type "$file")
if [[ "$mime" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file "$file" < /dev/null > /dev/tty
    read -rsn1
    exit 0
fi

if [[ "$mime" =~ ^text || "$mime" = application/json || "$mime" = application/x-ndjson || "$mime" = inode/x-empty ]]; then
    $EDITOR "$file"
    exit 0
fi

xdg-open "$file"
exit 0
