#!/usr/bin/env bash
file=$1

decompile() {
    java -jar /usr/share/java/cfr/cfr.jar "$1" | bat --language=java --color=always --paging=always --decorations=never
}

mime=$(file -Lb --mime-type "$file")
if [[ "$mime" =~ ^image/ ]]; then
    if [ "$TERM" = "xterm-kitty" ]; then
        kitty +kitten icat --silent --stdin no --transfer-mode file "$file" < /dev/null > /dev/tty
    elif [[ "$TERM" = "foot" || -n "$KONSOLE_VERSION" ]]; then
        chafa -f sixel "$1"
    fi
    read -rsn1
    exit 0
fi

if [[ "$mime" =~ ^text/ || "$mime" = application/json || "$mime" = application/x-ndjson || "$mime" = inode/x-empty || "$mime" = application/javascript ]]; then
    $EDITOR "$file"
    exit 0
fi

if [[ "$mime" = application/octet-stream ]]; then
    $EDITOR "$file"
    exit 0
fi

if [[ "$mime" = application/x-java-applet ]]; then
    decompile "$file"
    exit 0
fi

xdg-open "$file" &> /dev/null
