#!/bin/bash
foreground=#c0caf5
background=#1a1b26

color0=#414868
color8=#414868

color1=#f7768e
color9=#f7768e

color2=#73daca
color10=#73daca

color3=#e0af68
color11=#e0af68

color4=#7aa2f7
color12=#7aa2f7

color5=#bb9af7
color13=#bb9af7

color6=#7dcfff
color14=#7dcfff

color7=#a9b1d6
color15=#c0caf5

cursor_fg=#1a1b26
cursor_bg=#c0caf5

