## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Setups
format="$character$directory"
right_format = """$git_status$git_branch$cmd_duration"""
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
format = "$symbol"
success_symbol = "[ ](bg:#a6e3a1)"
error_symbol = "[ ](bg:#f38ba8)"
vicmd_symbol = "[](bg:#f9e2af fg:#11111b)"

[directory]
format = "[ 󰉋 ](bg:#11111b fg:#89b4fa)[$path](bg:#11111b fg:#BBC3DF bold)[ ]($style)"
style = "bg:none fg:#11111b"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#11111b fg:#A2DD9D bold)$branch](bg:#11111b fg:#86AAEC)[ ]($style)"
style = "bg:none fg:#11111b"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#11111b fg:#b4befe)[ ]($style)"
style = "bg:none fg:#11111b"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[ ](bg:#11111b fg:#eba0ac bold)$duration](bg:#11111b fg:#BBC3DF)[ ]($style)"
disabled = false
style = "bg:none fg:#11111b"

