#!/usr/bin/env bash
set -euo pipefail

#         

getstatus() {
    status=$(playerctl status)

    if [ "$status" = "Playing" ]; then
        echo " "
    elif [ "$status" = "Paused" ]; then
        echo " "
    else
        echo " "
    fi
}

gettitle() {
    playerctl metadata title
}

if [ "$1" = title ]; then
    dbus-monitor path='/org/mpris/MediaPlayer2',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged' --profile |
    while read -r _; do
        printf '{"text": "%s"}\n' "$(gettitle)"
    done
elif [ "$1" = status ]; then
    dbus-monitor path='/org/mpris/MediaPlayer2',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged' --profile |
    while read -r _; do
        printf '{"text": "%s"}\n' "$(getstatus)"
    done
fi

exit 0;
