#!/bin/sh

if [ ! -f "$2" ]; then
    exit 1
fi

. "$2"

case "$1" in
    gnome-terminal)
        default_profile="$(gsettings get org.gnome.Terminal.ProfilesList default | head -c -2 | tail -c +2)"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/palette "['$color0','$color1','$color2','$color3','$color4','$color5','$color6','$color7','$color8','$color9','$color10','$color11','$color12','$color13','$color14','$color15']"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/background-color "'$background'"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/foreground-color "'$foreground'"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/cursor-background-color "'$cursor_bg'"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/cursor-foreground-color "'$cursor_fg'"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/highlight-background-color "'$cursor_bg'"
        dconf write /org/gnome/terminal/legacy/profiles:/:$default_profile/highlight-foreground-color "'$cursor_fg'"
        ;;
esac
