#!/bin/sh

dex -ae river
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
waybar -c ~/.config/waybar/river.jsonc >/dev/null 2>&1 &
swaybg -i ~/.cache/swaybg/img &
/usr/lib/xdg-desktop-portal-wlr &
pkill -x swayidle; swayidle -C ~/.config/swayidle/river &
kanshi &
