#!/bin/sh

dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
waybar -c ~/.config/waybar/river.jsonc >/dev/null 2>&1 &
swaybg -i ~/.cache/swaybg/img &
pkill -x swayidle; swayidle -C ~/.config/swayidle/river &

