#!/bin/bash

riverctl set-repeat 30 200
riverctl keyboard-layout -options "grp:shift_caps_toggle" us,ru

riverctl focus-follows-cursor normal

inputs=($(riverctl list-inputs | grep "^pointer-" | grep -i "touchpad"))
for input in "${inputs[@]}"
do
    riverctl input "$input" tap enabled
    riverctl input "$input" disable-while-typing disabled
    riverctl input "$input" natural-scroll enabled
done
